Task 2.1. Header&Footer
VitaliiLazebnyi/reactjs_thinknetica pull request #2
Opened 2021-04-24 15:10 UTC by VitaliiLazebnyi

Task
----

1. Добавить Header с логотипом и Footer с копирайтом для нашего проекта, для создания макета страницы использовать фрагменты.

2. Добавить возможность вывести для книги несколько авторов. По-умолчанию выводить 3 автора. Если авторов больше 3, то вывести предложение отобразить всех c указанием количества. По нажатию на предложение отобразить список со всеми авторами. Проверить корректность задания ключа для элементов списка.

3. Добавить к информации о книге количество подписчиков. Выводить метку о популярности, если количество подписчиков превышает некоторый порог.

4. Добавить модальное окно с информацией об условиях подписки. (Например в зависимости от суммы перевода, можно поощрять подписчиков личной подписью автора, мерчендайзом (футболками, кружками), упоминанием в благодарностях).

2021-04-26 05:39 UTC, index01d requested changes

2021-04-26 05:39 UTC, index01d commented on src/components/Title.js
> +            </Modal>
Компонент `Title` стал отвечать за состояние модального окна, что в более сложных приложениях могло бы стать проблемой (нарушение принципа единственности ответственности может привести к переусложнению компонента Title).

Для решения можно было бы выделить компонент `<ModalButton component={MyModal} />` и оттащить управление состоянием модального окна в него.

2021-04-26 05:39 UTC, index01d commented on src/components/Header.js
> +class Header extends Component {
компоненты без состояния можно реализовать без использования классов

2021-04-26 05:39 UTC, index01d commented on src/components/Finance.js
> +                Subscribers number: {this.props.finance.subscribers}
свойства можно предварительно деструктурировать из свойств:
```js
const { subscribers, min_price, expected_price, ... } = this.props.finance;
```
тогда ниже не потребуется дублировать this.props.finance

2021-04-26 05:39 UTC, index01d commented on src/components/AuthorsList.js
> +    const authors = props.authors;
временная переменная выглядит избыточной

2021-04-26 05:39 UTC, index01d commented on src/components/Title.js
> +            </Modal>
Это замечание скорее общего характера и необязательно к мгновенному исправлению

2021-05-03 16:20 UTC, VitaliiLazebnyi commented on src/components/Header.js
> +class Header extends Component {
поменял

2021-05-04 08:38 UTC, VitaliiLazebnyi commented on src/components/Title.js
> +            </Modal>
готово

2021-05-04 16:00 UTC, index01d requested changes

2021-05-04 17:03 UTC, VitaliiLazebnyi commented on src/components/Finance.js
> +                Subscribers number: {this.props.finance.subscribers}
готово

2021-05-04 17:39 UTC, VitaliiLazebnyi commented on src/components/AuthorsList.js
> +    authorsList() {
ето ведь и есть код компонента <AuthorsList />

2021-05-04 17:42 UTC, VitaliiLazebnyi commented on src/components/Button.js
> +class Button extends Component {c
готово https://github.com/VitaliiLazebnyi/reactjs_thinknetica/pull/2/commits/6ab98341846a80175cfed0b3ebd669c2d2ad1df5

2021-05-04 17:44 UTC, VitaliiLazebnyi commented on src/components/Button.js
> +        this.button_text = this.props.button_text
готово https://github.com/VitaliiLazebnyi/reactjs_thinknetica/pull/2/commits/651ba86c44ee172fcb10a551370768f1e1867e53

2021-05-04 17:45 UTC, VitaliiLazebnyi commented on src/components/Button.js
> +    showModal = () => {
заменил синтаксис

2021-05-04 17:57 UTC, VitaliiLazebnyi commented on src/components/Title.js
> +            <Button button_text='subscribe' modal_text='Bay! Pay!' />
готово https://github.com/VitaliiLazebnyi/reactjs_thinknetica/pull/2/commits/d7a6ca700222a508722413e72e92907fd772978a + https://github.com/VitaliiLazebnyi/reactjs_thinknetica/pull/2/commits/f52019e23c248e0f816723d97f233de60ccc090c

2021-05-04 20:21 UTC, index01d approved these changes

2021-05-04 21:27 UTC, merged